version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mcp-file-tools
    main: ./cmd/mcp-file-tools
    binary: mcp-file-tools
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dimitar-grigorov/mcp-file-tools/filetoolsserver.Version={{.Version}}

archives:
  - id: default
    formats: ['tar.gz', 'zip']
    files:
      - README.md
      - LICENSE
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

# Also publish raw binaries for MCP registry (GoReleaser adds .exe automatically for Windows)
  - id: binaries
    formats: ['binary']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: dimitar-grigorov
    name: mcp-file-tools

# MCP Registry publishing
# Disabled: MCP registry now requires fileSha256 checksums which GoReleaser doesn't support yet
# See: https://github.com/orgs/goreleaser/discussions/6251
# TODO: Re-enable when GoReleaser adds checksum support for mcpb registry type
# mcp:
#   name: io.github.dimitar-grigorov/mcp-file-tools
#   title: MCP File Tools
#   description: "MCP server for reading/writing legacy-encoded files (CP1251, Windows-1251, etc.)"
#   homepage: https://github.com/dimitar-grigorov/mcp-file-tools
#   repository:
#     url: https://github.com/dimitar-grigorov/mcp-file-tools
#     source: github
#   auth:
#     type: github-oidc
#   disable: auto
#   packages:
#     - registry_type: mcpb
#       identifier: "https://github.com/dimitar-grigorov/mcp-file-tools/releases/download/v{{ .Version }}/mcp-file-tools_windows_amd64.exe"
#       transport:
#         type: stdio
